apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-ramped
  labels:
    app: my-app-ramped
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-app-ramped
  template:
    metadata:
      labels:
        app: my-app-ramped
        version: v3.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      containers:
      - name: my-app-ramped
        image: nginx
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
        env:
        - name: VERSION
          value: v3.0.0