apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-recreate
  labels:
    app: my-app-recreate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: my-app-recreate
  template:
    metadata:
      labels:
        app: my-app-recreate
        version: v2.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      containers:
      - name: my-app-recreate
        image: nginx
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
        env:
        - name: VERSION
          value: v2.0.0